"""Shared defaults for YouTube Shorts rendering and quality checks."""

TARGET_WIDTH = 1080
TARGET_HEIGHT = 1920
TARGET_ASPECT_RATIO = "9:16"
TARGET_FPS = 30

DEFAULT_VIDEO_CODEC = "libx264"
DEFAULT_AUDIO_CODEC = "aac"
DEFAULT_PIX_FMT = "yuv420p"
DEFAULT_CRF = 20
DEFAULT_PRESET = "medium"

DEFAULT_BGM_VOLUME_DB = -26
DEFAULT_BGM_FADE_IN_MS = 500
DEFAULT_BGM_FADE_OUT_MS = 1200

DEFAULT_SUBTITLE_FONT_NAME = "Noto Sans CJK JP"
DEFAULT_SUBTITLE_FONT_SIZE = 72
DEFAULT_SUBTITLE_PRIMARY_COLOR = "FFFFFF"
DEFAULT_SUBTITLE_OUTLINE_COLOR = "000000"
DEFAULT_SUBTITLE_OUTLINE = 5
DEFAULT_SUBTITLE_SHADOW = 1
DEFAULT_SUBTITLE_ALIGNMENT = "bottom_center"
DEFAULT_SUBTITLE_MARGIN_V = 220

MAX_SUBTITLE_CHARS = 32
MIN_SUBTITLE_DURATION_SEC = 1.2
MAX_BGM_VOLUME_DB = -22
MAX_DURATION_DIFF_SEC = 1.0
