"""Shared defaults for YouTube Shorts rendering and quality checks."""

TARGET_WIDTH = 1080
TARGET_HEIGHT = 1920
TARGET_ASPECT_RATIO = "9:16"
TARGET_FPS = 30
MAX_SHORTS_DURATION_SEC = 60.0

DEFAULT_VIDEO_CODEC = "libx264"
DEFAULT_AUDIO_CODEC = "aac"
DEFAULT_PIX_FMT = "yuv420p"
DEFAULT_CRF = 20
DEFAULT_PRESET = "medium"

DEFAULT_BGM_VOLUME_DB = -26
DEFAULT_BGM_FADE_IN_MS = 500
DEFAULT_BGM_FADE_OUT_MS = 1200

DEFAULT_SUBTITLE_FONT_NAME = "Yu Gothic UI Semibold"
DEFAULT_SUBTITLE_FONT_SIZE = 72
DEFAULT_SUBTITLE_PRIMARY_COLOR = "FFFFFF"
DEFAULT_SUBTITLE_OUTLINE_COLOR = "000000"
DEFAULT_SUBTITLE_OUTLINE = 5
DEFAULT_SUBTITLE_SHADOW = 1
DEFAULT_SUBTITLE_ALIGNMENT = "bottom_center"
DEFAULT_SUBTITLE_MARGIN_V = 220
DEFAULT_NARRATION_PEAK_DBFS = -3.0

MAX_SUBTITLE_CHARS = 32
MIN_SUBTITLE_DURATION_SEC = 1.2
MAX_SUBTITLE_CPS = 16.0
MAX_SUBTITLE_LINES = 2
MAX_BGM_VOLUME_DB = -22
MAX_DURATION_DIFF_SEC = 1.0
OPENING_SILENCE_SEC = 0.5
SILENCE_DBFS_THRESHOLD = -50.0
AUDIO_CLIPPING_DBFS_THRESHOLD = -0.1
MAX_FINAL_AUDIO_DURATION_DIFF_SEC = 0.1
MIN_SOURCE_SHORT_EDGE = 720
MAX_VIDEO_FILE_SIZE_MB = 200
